name: paynow_e_wallet_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  device_preview: ^1.2.0
  dio: ^5.7.0
  equatable: ^2.0.7
  logging: ^1.3.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.2.1
  photo_view: ^0.15.0
  webview_flutter: ^4.4.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  grouped_list: ^6.0.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  firebase_core: ^3.9.0
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  rename: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - lib/.env
  fonts:
    - family: SFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
        # - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
        # - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
        # - asset: assets/fonts/SF-Pro-Rounded-SemiBold.otf
        # - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
