// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA79LdL-xXd0KwP3Mq3WrX1RJBfqFlhWOc',
    appId: '1:165113372050:web:4646df85212ee23b0ab54b',
    messagingSenderId: '165113372050',
    projectId: 'pay-now-e-wallet-app-37dfd',
    authDomain: 'pay-now-e-wallet-app-37dfd.firebaseapp.com',
    storageBucket: 'pay-now-e-wallet-app-37dfd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL29glkQV_x3di3o4s7ev99RWbZDnp2Sg',
    appId: '1:165113372050:android:5aee00ca52d6ffe80ab54b',
    messagingSenderId: '165113372050',
    projectId: 'pay-now-e-wallet-app-37dfd',
    storageBucket: 'pay-now-e-wallet-app-37dfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsqK0zTJKzC9JSyMJzoccetHzWIr5lJVM',
    appId: '1:165113372050:ios:3c72d6c4992f0cb40ab54b',
    messagingSenderId: '165113372050',
    projectId: 'pay-now-e-wallet-app-37dfd',
    storageBucket: 'pay-now-e-wallet-app-37dfd.firebasestorage.app',
    iosBundleId: 'com.example.paynowEWalletApp',
  );

}