// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY']!,
    appId: '1:573832821000:web:fa444d01ccc0a807b4d4bd',
    messagingSenderId: '573832821000',
    projectId: 'pay-now-e-wallet-app-65b51',
    authDomain: 'pay-now-e-wallet-app-65b51.firebaseapp.com',
    storageBucket: 'pay-now-e-wallet-app-65b51.firebasestorage.app',
    measurementId: 'G-MFD6F8RLR8',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: '1:573832821000:android:6d2db80730c9118bb4d4bd',
    messagingSenderId: '573832821000',
    projectId: 'pay-now-e-wallet-app-65b51',
    storageBucket: 'pay-now-e-wallet-app-65b51.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: '1:573832821000:ios:d7464916bd722e7fb4d4bd',
    messagingSenderId: '573832821000',
    projectId: 'pay-now-e-wallet-app-65b51',
    storageBucket: 'pay-now-e-wallet-app-65b51.firebasestorage.app',
    iosBundleId: 'com.example.paynowEWalletApp',
  );
}
